const ACCESS_TOKEN_DURATION = 7;
const PRESERVE_LOGS_DAYS = 30;
const REFRESH_TOKEN_DURATION = 30;
const OTP_RESEND_DELAY = 120;
export { ACCESS_TOKEN_DURATION, REFRESH_TOKEN_DURATION, OTP_RESEND_DELAY, PRESERVE_LOGS_DAYS };